export type CategoryGroup = {
  id: string;
  label: string;
  osmTags: string[];
  keywords: string[];
};

export const CATEGORY_GROUPS: CategoryGroup[] = [
  {
    id: "food",
    label: "Restaurantes, lanchonetes, cafeterias e padarias",
    osmTags: [
      'nwr["amenity"="restaurant"]',
      'nwr["amenity"="fast_food"]',
      'nwr["amenity"="cafe"]',
      'nwr["shop"="bakery"]',
    ],
    keywords: [
      "restaurante",
      "lanchonete",
      "cafeteria",
      "padaria",
      "pizzaria",
      "hamburgueria",
      "bares",
      "pub",
      "cafe",
      "confeitaria",
      "doceria",
      "sorveteria",
      "churrascaria",
      "food truck",
      "delivery de comida",
      "marmitaria",
      "bistro",
    ],
  },
  {
    id: "beauty",
    label: "Barbearias, salões e clínicas de estética",
    osmTags: [
      'nwr["shop"="hairdresser"]',
      'nwr["shop"="beauty"]',
      'nwr["amenity"="beauty"]',
    ],
    keywords: [
      "barbearia",
      "salao",
      "estetica",
      "barbeiro",
      "cabeleireiro",
      "manicure",
      "pedicure",
      "unhas",
      "sobrancelha",
      "depilacao",
      "spa",
      "maquiagem",
      "esteticista",
      "salao de beleza",
      "beleza",
    ],
  },
  {
    id: "fitness",
    label: "Academias e estúdios",
    osmTags: ['nwr["leisure"="fitness_centre"]', 'nwr["sport"="fitness"]'],
    keywords: [
      "academia",
      "estudio",
      "crossfit",
      "pilates",
      "musculacao",
      "personal trainer",
      "yoga",
      "funcional",
      "box",
      "danca",
      "artes marciais",
      "jiu jitsu",
      "natacao",
    ],
  },
  {
    id: "pet",
    label: "Pet shops e clínicas veterinárias",
    osmTags: ['nwr["shop"="pet"]', 'nwr["amenity"="veterinary"]'],
    keywords: [
      "pet",
      "veterinaria",
      "veterinario",
      "petshop",
      "banho e tosa",
      "clinica veterinaria",
      "agropecuaria",
      "animais",
    ],
  },
  {
    id: "auto",
    label: "Oficinas e centros automotivos",
    osmTags: ['nwr["shop"="car_repair"]', 'nwr["amenity"="car_wash"]'],
    keywords: [
      "oficina",
      "automotivo",
      "mecanica",
      "mecanico",
      "funilaria",
      "lava jato",
      "lava rapido",
      "lava-rapido",
      "estetica automotiva",
      "auto center",
      "borracharia",
      "pneus",
      "eletrica automotiva",
      "martelinho",
      "insulfilm",
    ],
  },
  {
    id: "education",
    label: "Escolas, cursos e reforço escolar",
    osmTags: [
      'nwr["amenity"="school"]',
      'nwr["amenity"="college"]',
      'nwr["amenity"="language_school"]',
    ],
    keywords: [
      "escola",
      "curso",
      "reforco",
      "colegio",
      "creche",
      "bercario",
      "idiomas",
      "ingles",
      "pre vestibular",
      "concursos",
      "autoescola",
      "professor",
      "aulas particulares",
      "faculdade",
      "tecnico",
    ],
  },
  {
    id: "retail",
    label: "Lojas de roupas, móveis, materiais e eletrônicos",
    osmTags: [
      'nwr["shop"="clothes"]',
      'nwr["shop"="furniture"]',
      'nwr["shop"="electronics"]',
      'nwr["shop"="doityourself"]',
    ],
    keywords: [
      "roupas",
      "moveis",
      "eletronicos",
      "loja",
      "boutique",
      "calcados",
      "papelaria",
      "material de construcao",
      "otica",
      "joalheria",
      "brinquedos",
      "livraria",
      "farmacia",
      "mercado",
      "floricultura",
      "presentes",
    ],
  },
  {
    id: "events",
    label: "Fotógrafos e espaços de eventos",
    osmTags: [
      'nwr["craft"="photographer"]',
      'nwr["amenity"="events_venue"]',
      'nwr["leisure"="dance"]',
    ],
    keywords: [
      "fotografo",
      "eventos",
      "fotografia",
      "filmagem",
      "buffet",
      "salao de festas",
      "casamento",
      "cerimonial",
      "decoracao de eventos",
      "espaco para eventos",
      "video",
    ],
  },
  {
    id: "realestate",
    label: "Imobiliárias",
    osmTags: ['nwr["office"="estate_agent"]'],
    keywords: [
      "imobiliaria",
      "corretor",
      "imoveis",
      "aluguel de imoveis",
      "corretagem",
      "administradora de condominios",
    ],
  },
  {
    id: "professional",
    label: "Escritórios de contabilidade e advocacia",
    osmTags: [
      'nwr["office"="accountant"]',
      'nwr["office"="lawyer"]',
      'nwr["office"="tax_advisor"]',
    ],
    keywords: [
      "contabilidade",
      "advocacia",
      "advogado",
      "advogada",
      "contador",
      "escritorio de advocacia",
      "juridico",
      "assessoria contabil",
      "consultoria contabil",
      "consultoria juridica",
      "consultoria tributaria",
      "despachante",
      "arquitetura",
      "arquiteto",
      "engenharia",
      "engenheiro",
      "corretora de seguros",
      "corretor de seguros",
      "seguros",
    ],
  },
  {
    id: "health",
    label: "Consultórios e clínicas",
    osmTags: [
      'nwr["amenity"="doctors"]',
      'nwr["amenity"="clinic"]',
      'nwr["amenity"="dentist"]',
    ],
    keywords: [
      "consultorio",
      "clinica",
      "dentista",
      "odontologia",
      "medico",
      "psicologo",
      "psicologia",
      "fisioterapia",
      "nutricionista",
      "nutricao",
      "fonoaudiologia",
      "laboratorio",
      "exames",
      "terapia",
      "saude",
      "dermatologia",
      "oftalmologia",
      "pediatria",
    ],
  },
  {
    id: "services",
    label: "Prestadores de serviços locais",
    osmTags: ['nwr["office"="company"]', 'nwr["craft"]', 'nwr["shop"="laundry"]'],
    keywords: [
      "servicos",
      "lavanderia",
      "chaveiro",
      "eletricista",
      "encanador",
      "pintor",
      "marceneiro",
      "serralheria",
      "grafica",
      "assistencia tecnica",
      "dedetizacao",
      "limpeza",
      "jardinagem",
      "mudancas",
      "reformas",
      "reforma",
      "construcao",
      "ar condicionado",
      "ar-condicionado",
      "refrigeracao",
      "piscina",
      "informatica",
      "costura",
    ],
  },
  {
    id: "tourism",
    label: "Hotéis, pousadas e turismo",
    osmTags: [
      'nwr["tourism"="hotel"]',
      'nwr["tourism"="guest_house"]',
      'nwr["tourism"="hostel"]',
    ],
    keywords: [
      "hotel",
      "pousada",
      "turismo",
      "hostel",
      "chale",
      "resort",
      "agencia de viagens",
      "camping",
      "hospedagem",
    ],
  },
  {
    id: "catalog",
    label: "Negócios com catálogo, reservas, cardápio ou orçamento",
    osmTags: [
      'nwr["amenity"="restaurant"]',
      'nwr["tourism"="hotel"]',
      'nwr["shop"="florist"]',
    ],
    keywords: [
      "catalogo",
      "reservas",
      "cardapio",
      "orcamento",
      "atacado",
      "distribuidora",
      "representacao comercial",
    ],
  },
];

export function categoryLabelFromOsm(tags: Record<string, string>): string {
  if (tags.amenity === "restaurant" || tags.amenity === "fast_food") return "Restaurantes";
  if (tags.amenity === "cafe") return "Cafeterias";
  if (tags.shop === "bakery") return "Padarias";
  if (tags.shop === "hairdresser") return "Barbearias e salões";
  if (tags.shop === "beauty") return "Estética";
  if (tags.leisure === "fitness_centre") return "Academias";
  if (tags.shop === "pet") return "Pet shops";
  if (tags.amenity === "veterinary") return "Clínicas veterinárias";
  if (tags.shop === "car_repair") return "Oficinas automotivas";
  if (tags.amenity === "school" || tags.amenity === "college") return "Escolas e cursos";
  if (tags.shop === "clothes") return "Lojas de roupas";
  if (tags.shop === "furniture") return "Lojas de móveis";
  if (tags.shop === "electronics") return "Eletrônicos";
  if (tags.office === "estate_agent") return "Imobiliárias";
  if (tags.office === "accountant") return "Contabilidade";
  if (tags.office === "lawyer") return "Advocacia";
  if (tags.amenity === "clinic" || tags.amenity === "doctors") return "Clínicas";
  if (tags.tourism === "hotel" || tags.tourism === "guest_house") return "Hotéis e pousadas";
  if (tags.shop) return `Comércio (${tags.shop})`;
  if (tags.amenity) return `Serviço (${tags.amenity})`;
  if (tags.office) return `Escritório (${tags.office})`;
  return "Serviços locais";
}
